name: secure_vault
description: Secure vault mobile application with adaptive deception
publish_to: 'none'

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

flutter:
  uses-material-design: true
